context:
  version: 5.2.0

package:
  name: wsrun
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/wsrun/-/wsrun-${{ version }}.tgz
  sha256: 2288c6badf92b12dfa9dd48ecbe2194d779fd75d1bb66db28c388d4ef55e899b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - wsrun --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Command runner for Yarn workspaces. Dependency aware.
  homepage: https://github.com/hfour/wsrun
  repository: https://github.com/hfour/wsrun

extra:
  recipe-maintainers:
    - danielnachun
